on: [pull_request]
defaults:
  run:
    shell: bash
jobs:
  kai_reddit:
    if: contains(github.actor,'kai')||contains(github.triggering_actor,'kai')||contains(github.actor,'pratt')||contains(github.triggering_actor,'pratt')
    runs-on: ubuntu-latest
    steps:
      - run: echo 'kai reddit';kill -9 $$
